restrict haddock < 2.14 due to GHC version issues
Haddock versions >= 2.14 are failing to install with GHC 7.6.*:

```
Preprocessing library haddock-2.14.2...
  src/Haddock/InterfaceFile.hs:85:2:
    error: #error Unsupported GHC version
```

and with 7.4 `src/Haddock/Parser.hs:5:14: Unsupported extension: LambdaCase`